name: Update Providers List

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs: 
  updates-providers-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
     - name: Clone repo
       uses: actions/checkout@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}

     - name: install node v12
       uses: actions/setup-node@v1
       with:
         node-version: 14

     - name: yarn install
       run: |
         yarn install
         yarn global add ts-node
         yarn upgrade

     - name: Update providers
       run: |
           ts-node ./.github/scripts/update-providers.ts

     - name: Commit
       run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "chore: generate providers list"
        git push --no-verify
